
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async createProjectCommand(name: string, frameRate: number | null, resolutionWidth: number | null, resolutionHeight: number | null) : Promise<Result<Project, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_project_command", { name, frameRate, resolutionWidth, resolutionHeight }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAllProjectsCommand() : Promise<Result<Project[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_all_projects_command") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getProjectCommand(projectId: number) : Promise<Result<Project, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_project_command", { projectId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addAssetCommand(projectId: number, filePath: string, assetType: string, durationMs: number | null, width: number | null, height: number | null, fileSizeBytes: number) : Promise<Result<Asset, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_asset_command", { projectId, filePath, assetType, durationMs, width, height, fileSizeBytes }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAssetsCommand(projectId: number) : Promise<Result<Asset[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_assets_command", { projectId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createTrackWithClipCommand(projectId: number, assetId: number, trackType: string, startTimeMs: number) : Promise<Result<TrackWithClip, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_track_with_clip_command", { projectId, assetId, trackType, startTimeMs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTracksCommand(projectId: number) : Promise<Result<Track[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_tracks_command", { projectId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type Asset = { id: number; project_id: number; file_path: string; asset_type: string; duration_ms: number | null; width: number | null; height: number | null; file_size_bytes: number; imported_at: string }
export type Clip = { id: number; track_id: number; asset_id: number | null; start_time_ms: number; duration_ms: number; asset_start_offset_ms: number; asset_end_offset_ms: number; volume: number; is_muted: boolean }
export type Project = { id: number; name: string; duration_ms: number; frame_rate: number; resolution_width: number; resolution_height: number; created_at: string; updated_at: string }
export type Track = { id: number; project_id: number; track_type: string; order_index: number; is_locked: boolean; is_muted: boolean }
export type TrackWithClip = { track: Track; clip: Clip }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
